
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

const translations = {
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.services': 'Leistungen',
    'nav.solutions': 'Lösungen',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Kontakt',
    'nav.book': 'Termin buchen',
    
    // Hero
    'hero.title': 'Dein Partner für digitale Transformation',
    'hero.subtitle': 'Marketing, Multimedia, Web Development, Webdesign & KI Consulting',
    'hero.cta': 'Jetzt Kontakt aufnehmen',
    
    // About
    'about.hero.title': 'Über uns',
    'about.hero.subtitle': 'Lerne unser Team und unsere Mission kennen',
    'about.story.title': 'Unsere Geschichte',
    'about.story.p1': 'Gegründet im Jahr 2015, begann unser Unternehmen mit einer einfachen Mission: Unternehmen dabei zu helfen, in der digitalen Welt erfolgreich zu sein. Was als kleines Team von Entwicklern und Designern begann, hat sich zu einer Full-Service-Digitalagentur entwickelt.',
    'about.story.p2': 'Im Laufe der Jahre haben wir mit Hunderten von Kunden aus verschiedenen Branchen zusammengearbeitet und ihnen geholfen, ihre digitale Präsenz aufzubauen, ihre Reichweite zu vergrößern und ihre Geschäftsziele zu erreichen.',
    'about.story.p3': 'Heute sind wir ein vielfältiges Team von Experten, die sich leidenschaftlich für die Bereitstellung innovativer digitaler Lösungen einsetzen, die echte Ergebnisse liefern.',
    'about.values.title': 'Unsere Werte',
    'about.values.subtitle': 'Diese Grundsätze leiten unsere tägliche Arbeit und Entscheidungen',
    'about.values.v1.title': 'Kundenorientierung',
    'about.values.v1.description': 'Wir stellen die Bedürfnisse unserer Kunden in den Mittelpunkt all unserer Aktivitäten und streben danach, Erwartungen zu übertreffen.',
    'about.values.v2.title': 'Exzellenz',
    'about.values.v2.description': 'Wir verpflichten uns zu höchster Qualität in allem, was wir tun, von der Entwicklung bis zum Kundenservice.',
    'about.values.v3.title': 'Innovation',
    'about.values.v3.description': 'Wir bleiben an der Spitze der technologischen Trends und setzen kontinuierlich neue Ideen um, um bessere Ergebnisse zu erzielen.',
    'about.values.v4.title': 'Effizienz',
    'about.values.v4.description': 'Wir optimieren unsere Prozesse, um qualitativ hochwertige Lösungen termingerecht und innerhalb des Budgets zu liefern.',
    'about.values.v5.title': 'Ergebnisorientierung',
    'about.values.v5.description': 'Wir konzentrieren uns auf messbare Ergebnisse, die einen tatsächlichen Geschäftswert für unsere Kunden schaffen.',
    'about.values.v6.title': 'Datengesteuert',
    'about.values.v6.description': 'Wir treffen informierte Entscheidungen auf Basis von Daten und Analysen, um die besten Ergebnisse zu erzielen.',
    'about.cta.title': 'Bereit, mit uns zusammenzuarbeiten?',
    'about.cta.description': 'Lass uns über dein nächstes Projekt sprechen und wie wir dir helfen können, deine Ziele zu erreichen.',
    'about.cta.contact': 'Kontakt aufnehmen',
    'about.cta.portfolio': 'Portfolio ansehen',
    
    // Services
    'services.title': 'Unsere Leistungen',
    'services.subtitle': 'Was wir für dich tun können',
    'services.consulting.title': 'Consulting',
    'services.consulting.description': 'Professionelle Beratung für deine digitalen Herausforderungen',
    'services.development.title': 'Development',
    'services.development.description': 'Maßgeschneiderte Softwarelösungen für dein Unternehmen',
    'services.coaching.title': 'Coaching',
    'services.coaching.description': 'Individuelle Schulungen und Workshops für dein Team',
    'services.learnMore': 'Mehr erfahren',
    'services.web.title': 'Web Development',
    'services.web.description': 'Moderne, responsive Websites und Webanwendungen mit den neuesten Technologien',
    'services.design.title': 'UI/UX Design',
    'services.design.description': 'Nutzerzentriertes Design, das intuitive, ansprechende Erlebnisse über alle Plattformen hinweg schafft',
    'services.marketing.title': 'Digital Marketing',
    'services.marketing.description': 'Datengesteuerte Marketingstrategien, die die Sichtbarkeit erhöhen und Conversions steigern',
    'services.mobile.title': 'Mobile Entwicklung',
    'services.mobile.description': 'Native und plattformübergreifende mobile Apps für iOS und Android',
    'services.ai.title': 'KI & Machine Learning',
    'services.ai.description': 'Intelligente Lösungen, die von modernster KI und maschinellem Lernen angetrieben werden',
    'services.ecommerce.title': 'E-Commerce-Lösungen',
    'services.ecommerce.description': 'End-to-End E-Commerce-Plattformen, optimiert für Conversions und Kundenbindung',
    'services.toast.title': 'Service ausgewählt',
    'services.toast.description': 'Vielen Dank für dein Interesse! Wir werden uns in Kürze mit dir in Verbindung setzen.',
    'services.hero.title': 'Unsere Dienstleistungen',
    'services.hero.subtitle': 'Maßgeschneiderte Lösungen für deine digitalen Herausforderungen',
    'services.main.title': 'Wir helfen dir, online erfolgreich zu sein',
    'services.main.subtitle': 'Unsere umfassenden Dienstleistungen unterstützen dich bei jedem Schritt deiner digitalen Reise',
    'services.process.title': 'Unser Prozess',
    'services.process.subtitle': 'Wie wir arbeiten, um deine Ziele zu erreichen',
    'services.process.discovery': 'Entdeckung',
    'services.process.discoveryDesc': 'Wir verstehen deine Bedürfnisse, Ziele und Herausforderungen',
    'services.process.strategy': 'Strategie',
    'services.process.strategyDesc': 'Wir entwickeln einen maßgeschneiderten Plan, um deine Ziele zu erreichen',
    'services.process.execution': 'Ausführung',
    'services.process.executionDesc': 'Wir setzen die Strategie mit Präzision und Qualität um',
    'services.process.optimization': 'Optimierung',
    'services.process.optimizationDesc': 'Wir optimieren kontinuierlich für beste Ergebnisse',
    'services.cta.title': 'Bereit für den nächsten Schritt?',
    'services.cta.description': 'Lass uns besprechen, wie wir dir bei deinem nächsten Projekt helfen können',
    'services.cta.contact': 'Kontakt aufnehmen',
    'services.cta.schedule': 'Termin vereinbaren',
    'services.products.title': 'Produkte',
    'services.products.description': 'Fertige Lösungen, die sofort eingesetzt werden können',
    'services.services.title': 'Dienstleistungen',
    'services.services.description': 'Professionelle Services für deine individuellen Bedürfnisse',
    
    // Solutions
    'solutions.title': 'Unsere Lösungen',
    'solutions.subtitle': 'Innovative Lösungen für deine Anforderungen',
    'solutions.learnMore': 'Mehr erfahren',
    'solutions.hero.title': 'Branchenspezifische Lösungen',
    'solutions.hero.subtitle': 'Maßgeschneiderte Strategien für verschiedene Geschäftsbereiche',
    'solutions.industries.title': 'Branchen, die wir bedienen',
    'solutions.industries.subtitle': 'Spezialisierte Lösungen für verschiedene Sektoren',
    'solutions.industries.business.title': 'Business Solutions',
    'solutions.industries.business.description': 'Umfassende digitale Transformationslösungen für kleine bis mittlere Unternehmen',
    'solutions.industries.businesssolutions.feature1': 'Optimierte Geschäftsprozesse',
    'solutions.industries.businesssolutions.feature2': 'Skalierbare Infrastruktur',
    'solutions.industries.businesssolutions.feature3': 'Kundenorientierte Systeme',
    'solutions.industries.ecommerce.title': 'E-Commerce',
    'solutions.industries.ecommerce.description': 'End-to-End-Online-Verkaufsplattformen mit Bestandsverwaltung und Zahlungsabwicklung',
    'solutions.industries.e-commerce.feature1': 'Nahtlose Checkout-Erfahrung',
    'solutions.industries.e-commerce.feature2': 'Integrierte Zahlungsabwicklung',
    'solutions.industries.e-commerce.feature3': 'Mobile Optimierung',
    'solutions.industries.corporate.title': 'Corporate Services',
    'solutions.industries.corporate.description': 'Digitale Lösungen auf Unternehmensebene für große Organisationen und Konzerne',
    'solutions.industries.corporateservices.feature1': 'Unternehmensweite Integration',
    'solutions.industries.corporateservices.feature2': 'Robuste Sicherheitsmaßnahmen',
    'solutions.industries.corporateservices.feature3': 'Compliance-Management',
    'solutions.industries.education.title': 'Bildung',
    'solutions.industries.education.description': 'Lernmanagementsysteme und Bildungsplattformen für Schulen und Universitäten',
    'solutions.industries.education.feature1': 'Interaktive Lernumgebungen',
    'solutions.industries.education.feature2': 'Fortschrittsverfolgung',
    'solutions.industries.education.feature3': 'Virtuelle Klassenzimmer',
    'solutions.industries.healthcare.title': 'Gesundheitswesen',
    'solutions.industries.healthcare.description': 'Digitale Gesundheitslösungen einschließlich Patientenmanagement und Telemedizin',
    'solutions.industries.healthcare.feature1': 'Sichere Patientendaten',
    'solutions.industries.healthcare.feature2': 'Telemedizin-Integration',
    'solutions.industries.healthcare.feature3': 'Compliance mit Gesundheitsvorschriften',
    'solutions.industries.startup.title': 'Startups',
    'solutions.industries.startup.description': 'Agile, skalierbare Lösungen speziell für Startups und neue Unternehmen',
    'solutions.industries.startups.feature1': 'Schnelle Markteinführung',
    'solutions.industries.startups.feature2': 'Kosteneffiziente Lösungen',
    'solutions.industries.startups.feature3': 'Skalierbare Architektur',
    'solutions.caseStudies.title': 'Fallstudien',
    'solutions.caseStudies.subtitle': 'Erfolgsgeschichten unserer Kunden',
    'solutions.caseStudies.readCase': 'Fallstudie lesen',
    'solutions.caseStudies.case1.industry': 'E-Commerce',
    'solutions.caseStudies.case1.title': 'Umsatzsteigerung um 200% für Online-Einzelhändler',
    'solutions.caseStudies.case1.description': 'Wie wir einem aufstrebenden E-Commerce-Unternehmen geholfen haben, seinen Umsatz durch eine umfassende digitale Strategie zu verdreifachen',
    'solutions.caseStudies.case2.industry': 'Gesundheitswesen',
    'solutions.caseStudies.case2.title': 'Digitale Transformation für Gesundheitsdienstleister',
    'solutions.caseStudies.case2.description': 'Eine umfassende digitale Lösung, die die Patientenversorgung verbessert und die betriebliche Effizienz steigert',
    'solutions.cta.title': 'Lass uns deine Branchenlösung entwickeln',
    'solutions.cta.description': 'Kontaktiere uns für eine maßgeschneiderte Strategie, die auf deine spezifischen Branchenanforderungen zugeschnitten ist',
    'solutions.cta.contact': 'Kontakt aufnehmen',
    'solutions.cta.schedule': 'Termin vereinbaren',
    'solutions.cta.stat': '93% Kundenzufriedenheit',
    'solutions.cta.statDesc': 'Basierend auf unseren letzten 100 Projekten',
    'solutions.consulting.title': 'Beratung',
    'solutions.consulting.description': 'Strategische Beratung für die digitale Transformation deines Unternehmens',
    'solutions.products.title': 'Produkte',
    'solutions.products.description': 'Innovative Produktlösungen für deine Branchenanforderungen',
    'solutions.services.title': 'Services',
    'solutions.services.description': 'Maßgeschneiderte Dienstleistungen für nachhaltige Geschäftserfolge',
    
    // Portfolio
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Einige unserer Projekte',
    'portfolio.viewProject': 'Projekt ansehen',
    'portfolio.hero.title': 'Unser Portfolio',
    'portfolio.hero.subtitle': 'Entdecke unsere erfolgreichsten Projekte',
    'portfolio.projects.title': 'Ausgewählte Arbeiten',
    'portfolio.projects.subtitle': 'Eine Sammlung unserer besten Projekte aus verschiedenen Bereichen',
    'portfolio.projects.p1.title': 'E-Commerce Redesign',
    'portfolio.projects.p1.description': 'Komplettes Redesign einer E-Commerce-Plattform mit Fokus auf Benutzererfahrung und Conversion-Optimierung',
    'portfolio.projects.p2.title': 'KI-Integration',
    'portfolio.projects.p2.description': 'Integration einer KI-gestützten Empfehlungs-Engine für eine Content-Plattform zur Verbesserung des Benutzerengagements',
    'portfolio.projects.p3.title': 'Marketing-Kampagne',
    'portfolio.projects.p3.description': 'Multimedia-Marketingkampagne für eine Produkteinführung, einschließlich Web-, Social Media- und Druckmaterialien',
    'portfolio.projects.p4.title': 'Unternehmenswebsite',
    'portfolio.projects.p4.description': 'Moderne Unternehmenswebsite mit integriertem CMS für ein Finanzdienstleistungsunternehmen',
    'portfolio.projects.p5.title': 'Markenidentität',
    'portfolio.projects.p5.description': 'Komplettes Markenidentitätspaket für ein Tech-Startup, einschließlich Logo, Typografie und Markenrichtlinien',
    'portfolio.projects.p6.title': 'Mobile App',
    'portfolio.projects.p6.description': 'Funktionsreiche mobile Anwendung für eine Gesundheits- und Wellness-Plattform mit personalisierten Benutzererlebnissen',
    'portfolio.testimonials.title': 'Kundenstimmen',
    'portfolio.testimonials.subtitle': 'Was unsere Kunden über uns sagen',
    'portfolio.testimonials.t1.quote': 'Das Team hat unsere Erwartungen übertroffen. Sie haben nicht nur eine wunderschöne Website geliefert, sondern auch unser gesamtes digitales Marketingspiel verbessert.',
    'portfolio.testimonials.t2.quote': 'Die KI-Lösung, die sie für uns entwickelt haben, hat unser Benutzerengagement und unsere Conversion-Raten drastisch verbessert. Höchst empfohlen!',
    'portfolio.testimonials.t3.quote': 'Professionell, pünktlich und unglaublich talentiert. Sie haben unsere Vision verstanden und sie mit Präzision zum Leben erweckt.',
    'portfolio.cta.title': 'Bereit, an deinem Projekt zu arbeiten?',
    'portfolio.cta.description': 'Lass uns besprechen, wie wir deine Ideen zum Leben erwecken können',
    'portfolio.cta.contact': 'Kontakt aufnehmen',
    'portfolio.cta.schedule': 'Termin vereinbaren',
    
    // Contact
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Nimm Kontakt mit uns auf',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht senden',
    'contact.success': 'Deine Nachricht wurde erfolgreich gesendet!',
    'contact.error': 'Es ist ein Fehler aufgetreten. Bitte versuche es später erneut.',
    'contact.hero.title': 'Kontaktiere uns',
    'contact.hero.subtitle': 'Wir freuen uns, von dir zu hören',
    'contact.email.title': 'E-Mail',
    'contact.email.description': 'Schreib uns eine Nachricht, wir antworten innerhalb von 24 Stunden',
    'contact.phone.title': 'Telefon',
    'contact.phone.description': 'Ruf uns an für sofortige Unterstützung bei dringenden Anfragen',
    'contact.office.title': 'Büro',
    'contact.office.description': 'Besuche uns in unserem Hauptbüro für ein persönliches Gespräch',
    'contact.form.title': 'Schreib uns eine Nachricht',
    'contact.form.name': 'Dein Name',
    'contact.form.namePlaceholder': 'Name eingeben',
    'contact.form.email': 'Deine E-Mail',
    'contact.form.emailPlaceholder': 'E-Mail eingeben',
    'contact.form.subject': 'Betreff',
    'contact.form.subjectPlaceholder': 'Betreff eingeben',
    'contact.form.message': 'Deine Nachricht',
    'contact.form.messagePlaceholder': 'Wie können wir dir helfen?',
    'contact.form.submit': 'Nachricht senden',
    'contact.form.sending': 'Wird gesendet...',
    'contact.success.title': 'Nachricht gesendet!',
    'contact.success.description': 'Vielen Dank für deine Nachricht. Wir werden uns so schnell wie möglich bei dir melden.',
    'contact.error.title': 'Fehler',
    'contact.error.description': 'Beim Senden deiner Nachricht ist ein Fehler aufgetreten. Bitte versuche es später erneut.',
    'contact.office.hoursTitle': 'Bürozeiten & Standort',
    'contact.office.schedule': 'Termin planen',
    'contact.office.monday': 'Montag - Freitag',
    'contact.office.saturday': 'Samstag',
    'contact.office.sunday': 'Sonntag',
    'contact.office.closed': 'Geschlossen',
    'contact.faq.title': 'Häufig gestellte Fragen',
    'contact.faq.subtitle': 'Antworten auf die am häufigsten gestellten Fragen',
    'contact.faq.q1': 'Wie beginne ich ein Projekt mit euch?',
    'contact.faq.a1': 'Der erste Schritt ist, uns zu kontaktieren und uns etwas über dein Projekt zu erzählen. Wir werden dann ein Gespräch vereinbaren, um deine Anforderungen im Detail zu besprechen und einen Vorschlag zu erstellen.',
    'contact.faq.q2': 'Wie lange dauert es, ein Projekt abzuschließen?',
    'contact.faq.a2': 'Die Projektdauer hängt stark vom Umfang und der Komplexität ab. Ein einfaches Website-Redesign kann 2-4 Wochen dauern, während komplexere digitale Transformationsprojekte 3-6 Monate oder länger dauern können.',
    'contact.faq.q3': 'Welche Zahlungsbedingungen bietet ihr an?',
    'contact.faq.a3': 'Wir bieten flexible Zahlungsbedingungen, darunter Pauschalpreise für Projekte, Stundensätze für laufende Arbeiten und Retainer-Modelle für kontinuierliche Dienstleistungen. Für größere Projekte arbeiten wir in der Regel mit einer Anzahlung und dann nach Meilensteinen.',
    'contact.faq.q4': 'Arbeitet ihr mit Kunden außerhalb Deutschlands?',
    'contact.faq.a4': 'Ja, wir arbeiten mit Kunden weltweit zusammen. Unser Team ist es gewohnt, remote zu arbeiten und wir nutzen verschiedene Tools, um eine effektive Kommunikation und Zusammenarbeit über verschiedene Zeitzonen hinweg zu gewährleisten.',
    
    // Footer
    'footer.rights': 'Alle Rechte vorbehalten',
    'footer.privacy': 'Datenschutz',
    'footer.imprint': 'Impressum',
    'footer.cookies': 'Cookies',
    
    // Cookies
    'cookies.title': 'Cookie-Richtlinie',
    'cookies.subtitle': 'Wie wir Cookies verwenden, um dein Browsing-Erlebnis zu verbessern',
    'cookies.lastUpdated': 'Zuletzt aktualisiert',
    'cookies.whatAre.title': 'Was sind Cookies?',
    'cookies.whatAre.p1': 'Cookies sind kleine Textdateien, die auf deinem Computer oder Mobilgerät gespeichert werden, wenn du eine Website besuchst. Sie werden häufig verwendet, um Websites effizienter zu machen und dem Benutzer Informationen bereitzustellen.',
    'cookies.howWeUse.title': 'Wie wir Cookies verwenden',
    'cookies.howWeUse.p1': 'Wir verwenden Cookies, um dein Browsing-Erlebnis zu verbessern, die Website-Performance zu analysieren, personalisierte Inhalte anzubieten und unsere Marketingbemühungen zu unterstützen.',
    'cookies.types.title': 'Arten von Cookies, die wir verwenden',
    'cookies.types.account.title': 'Kontobezogene Cookies',
    'cookies.types.account.p1': 'Diese Cookies helfen uns, dich zu erkennen, wenn du dich anmeldest, und speichern deine Präferenzen für zukünftige Besuche.',
    'cookies.types.login.title': 'Login-bezogene Cookies',
    'cookies.types.login.p1': 'Diese Cookies werden verwendet, um deine Anmeldung zu ermöglichen und deine Sitzung während deines Besuchs auf unserer Website aufrechtzuerhalten.',
    'cookies.types.forms.title': 'Formular-bezogene Cookies',
    'cookies.types.forms.p1': 'Diese Cookies speichern Informationen, die du in Formulare auf unserer Website eingibst, wie Kontaktformulare oder Kommentare.',
    'cookies.types.site.title': 'Website-Präferenzen',
    'cookies.types.site.p1': 'Diese Cookies speichern deine Präferenzen, wie Spracheinstellungen, damit wir dir bei zukünftigen Besuchen ein personalisiertes Erlebnis bieten können.',
    'cookies.thirdParty.title': 'Cookies von Drittanbietern',
    'cookies.thirdParty.p1': 'Wir können auch Cookies von Drittanbietern zulassen, die uns helfen zu analysieren, wie Besucher unsere Website nutzen, und die Effektivität unserer Marketingbemühungen zu messen.',
    'cookies.thirdParty.analytics': 'Analytics-Cookies, um zu verstehen, wie Besucher mit unserer Website interagieren',
    'cookies.thirdParty.social': 'Social-Media-Cookies, um dir das Teilen von Inhalten zu ermöglichen',
    'cookies.disabling.title': 'Deaktivieren von Cookies',
    'cookies.disabling.p1': 'Du kannst die Verwendung von Cookies in deinen Browsereinstellungen steuern und verwalten. Beachte jedoch, dass die Deaktivierung von Cookies die Funktionalität unserer Website beeinträchtigen kann.',
    'cookies.more.title': 'Weitere Informationen',
    'cookies.more.p1': 'Wenn du Fragen zu unserer Cookie-Richtlinie hast oder mehr darüber erfahren möchtest, wie wir deine persönlichen Daten verarbeiten, lies bitte unsere Datenschutzrichtlinie.',
    'cookies.more.p2': 'Bei Fragen oder Anliegen kontaktiere uns bitte unter:',
    'cookies.more.email': 'E-Mail',
    'cookies.more.phone': 'Telefon',
    'cookies.backButton': 'Zurück zur vorherigen Seite',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.solutions': 'Solutions',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.book': 'Book Appointment',
    
    // Hero
    'hero.title': 'Your Partner for Digital Transformation',
    'hero.subtitle': 'Marketing, Multimedia, Web Development, Web Design & AI Consulting',
    'hero.cta': 'Get in Touch',
    
    // About
    'about.hero.title': 'About Us',
    'about.hero.subtitle': 'Get to know our team and our mission',
    'about.story.title': 'Our Story',
    'about.story.p1': 'Founded in 2015, our company began with a simple mission: to help businesses succeed in the digital world. What started as a small team of developers and designers has evolved into a full-service digital agency.',
    'about.story.p2': 'Over the years, we\'ve worked with hundreds of clients across various industries, helping them build their digital presence, expand their reach, and achieve their business goals.',
    'about.story.p3': 'Today, we are a diverse team of experts passionate about delivering innovative digital solutions that deliver real results.',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'These principles guide our daily work and decisions',
    'about.values.v1.title': 'Customer Focus',
    'about.values.v1.description': 'We center our clients\' needs in all our activities and strive to exceed expectations.',
    'about.values.v2.title': 'Excellence',
    'about.values.v2.description': 'We commit to the highest quality in everything we do, from development to customer service.',
    'about.values.v3.title': 'Innovation',
    'about.values.v3.description': 'We stay at the forefront of technological trends and continuously implement new ideas to achieve better results.',
    'about.values.v4.title': 'Efficiency',
    'about.values.v4.description': 'We optimize our processes to deliver high-quality solutions on time and within budget.',
    'about.values.v5.title': 'Result-Oriented',
    'about.values.v5.description': 'We focus on measurable outcomes that create actual business value for our clients.',
    'about.values.v6.title': 'Data-Driven',
    'about.values.v6.description': 'We make informed decisions based on data and analytics to achieve the best results.',
    'about.cta.title': 'Ready to work with us?',
    'about.cta.description': 'Let\'s talk about your next project and how we can help you achieve your goals.',
    'about.cta.contact': 'Get in Touch',
    'about.cta.portfolio': 'View Portfolio',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'What we can do for you',
    'services.consulting.title': 'Consulting',
    'services.consulting.description': 'Professional advice for your digital challenges',
    'services.development.title': 'Development',
    'services.development.description': 'Tailored software solutions for your business',
    'services.coaching.title': 'Coaching',
    'services.coaching.description': 'Individual training and workshops for your team',
    'services.learnMore': 'Learn More',
    'services.web.title': 'Web Development',
    'services.web.description': 'Modern, responsive websites and web applications built with the latest technologies',
    'services.design.title': 'UI/UX Design',
    'services.design.description': 'User-centered design that creates intuitive, engaging experiences across all platforms',
    'services.marketing.title': 'Digital Marketing',
    'services.marketing.description': 'Data-driven marketing strategies that increase visibility and drive conversions',
    'services.mobile.title': 'Mobile Development',
    'services.mobile.description': 'Native and cross-platform mobile apps for iOS and Android',
    'services.ai.title': 'AI & Machine Learning',
    'services.ai.description': 'Intelligent solutions powered by cutting-edge AI and machine learning',
    'services.ecommerce.title': 'E-Commerce Solutions',
    'services.ecommerce.description': 'End-to-end e-commerce platforms optimized for conversions and customer retention',
    'services.toast.title': 'Service Selected',
    'services.toast.description': 'Thank you for your interest! We will get in touch with you shortly.',
    'services.hero.title': 'Our Services',
    'services.hero.subtitle': 'Tailored solutions for your digital challenges',
    'services.main.title': 'We Help You Succeed Online',
    'services.main.subtitle': 'Our comprehensive services support you at every step of your digital journey',
    'services.process.title': 'Our Process',
    'services.process.subtitle': 'How we work to achieve your goals',
    'services.process.discovery': 'Discovery',
    'services.process.discoveryDesc': 'We understand your needs, goals, and challenges',
    'services.process.strategy': 'Strategy',
    'services.process.strategyDesc': 'We develop a tailored plan to achieve your objectives',
    'services.process.execution': 'Execution',
    'services.process.executionDesc': 'We implement the strategy with precision and quality',
    'services.process.optimization': 'Optimization',
    'services.process.optimizationDesc': 'We continuously optimize for best results',
    'services.cta.title': 'Ready for the Next Step?',
    'services.cta.description': 'Let\'s discuss how we can help with your next project',
    'services.cta.contact': 'Get in Touch',
    'services.cta.schedule': 'Schedule a Call',
    'services.products.title': 'Products',
    'services.products.description': 'Ready-made solutions that can be deployed immediately',
    'services.services.title': 'Services',
    'services.services.description': 'Professional services for your individual needs',
    
    // Solutions
    'solutions.title': 'Our Solutions',
    'solutions.subtitle': 'Innovative solutions for your requirements',
    'solutions.learnMore': 'Learn More',
    'solutions.hero.title': 'Industry-Specific Solutions',
    'solutions.hero.subtitle': 'Tailored strategies for different business sectors',
    'solutions.industries.title': 'Industries We Serve',
    'solutions.industries.subtitle': 'Specialized solutions for various sectors',
    'solutions.industries.business.title': 'Business Solutions',
    'solutions.industries.business.description': 'Comprehensive digital transformation solutions tailored for small to medium businesses',
    'solutions.industries.business.feature1': 'Streamlined business processes',
    'solutions.industries.business.feature2': 'Scalable infrastructure',
    'solutions.industries.business.feature3': 'Customer-focused systems',
    'solutions.industries.ecommerce.title': 'E-Commerce',
    'solutions.industries.ecommerce.description': 'End-to-end online sales platforms with inventory management and payment processing',
    'solutions.industries.ecommerce.feature1': 'Seamless checkout experience',
    'solutions.industries.ecommerce.feature2': 'Integrated payment processing',
    'solutions.industries.ecommerce.feature3': 'Mobile optimization',
    'solutions.industries.corporate.title': 'Corporate Services',
    'solutions.industries.corporate.description': 'Enterprise-grade digital solutions for large organizations and corporations',
    'solutions.industries.corporate.feature1': 'Enterprise-wide integration',
    'solutions.industries.corporate.feature2': 'Robust security measures',
    'solutions.industries.corporate.feature3': 'Compliance management',
    'solutions.industries.education.title': 'Education',
    'solutions.industries.education.description': 'Learning management systems and educational platforms for schools and universities',
    'solutions.industries.education.feature1': 'Interactive learning environments',
    'solutions.industries.education.feature2': 'Progress tracking',
    'solutions.industries.education.feature3': 'Virtual classrooms',
    'solutions.industries.healthcare.title': 'Healthcare',
    'solutions.industries.healthcare.description': 'Digital health solutions including patient management and telehealth services',
    'solutions.industries.healthcare.feature1': 'Secure patient data',
    'solutions.industries.healthcare.feature2': 'Telehealth integration',
    'solutions.industries.healthcare.feature3': 'Healthcare compliance',
    'solutions.industries.startup.title': 'Startups',
    'solutions.industries.startup.description': 'Agile, scalable solutions designed specifically for startups and new ventures',
    'solutions.industries.startup.feature1': 'Rapid time-to-market',
    'solutions.industries.startup.feature2': 'Cost-effective solutions',
    'solutions.industries.startup.feature3': 'Scalable architecture',
    'solutions.caseStudies.title': 'Case Studies',
    'solutions.caseStudies.subtitle': 'Success stories from our clients',
    'solutions.caseStudies.readCase': 'Read Case Study',
    'solutions.caseStudies.case1.industry': 'E-Commerce',
    'solutions.caseStudies.case1.title': '200% Revenue Increase for Online Retailer',
    'solutions.caseStudies.case1.description': 'How we helped an emerging e-commerce business triple their revenue through a comprehensive digital strategy',
    'solutions.caseStudies.case2.industry': 'Healthcare',
    'solutions.caseStudies.case2.title': 'Digital Transformation for Healthcare Provider',
    'solutions.caseStudies.case2.description': 'A comprehensive digital solution that improved patient care and operational efficiency',
    'solutions.cta.title': 'Let\'s Build Your Industry Solution',
    'solutions.cta.description': 'Contact us for a tailored strategy designed for your specific industry needs',
    'solutions.cta.contact': 'Get in Touch',
    'solutions.cta.schedule': 'Schedule a Call',
    'solutions.cta.stat': '93% Client Satisfaction',
    'solutions.cta.statDesc': 'Based on our last 100 projects',
    'solutions.consulting.title': 'Consulting',
    'solutions.consulting.description': 'Strategic consulting for your business\'s digital transformation',
    'solutions.products.title': 'Products',
    'solutions.products.description': 'Innovative product solutions for your industry requirements',
    'solutions.services.title': 'Services',
    'solutions.services.description': 'Tailored services for sustainable business success',
    
    // Portfolio
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Some of our projects',
    'portfolio.viewProject': 'View Project',
    'portfolio.hero.title': 'Our Portfolio',
    'portfolio.hero.subtitle': 'Discover our most successful projects',
    'portfolio.projects.title': 'Featured Work',
    'portfolio.projects.subtitle': 'A collection of our best projects across different domains',
    'portfolio.projects.p1.title': 'E-Commerce Redesign',
    'portfolio.projects.p1.description': 'Complete redesign of an e-commerce platform with focus on user experience and conversion optimization',
    'portfolio.projects.p2.title': 'AI Integration',
    'portfolio.projects.p2.description': 'Integration of AI-powered recommendation engine for a content platform to improve user engagement',
    'portfolio.projects.p3.title': 'Marketing Campaign',
    'portfolio.projects.p3.description': 'Multimedia marketing campaign for a product launch, including web, social media, and print materials',
    'portfolio.projects.p4.title': 'Corporate Website',
    'portfolio.projects.p4.description': 'Modern corporate website with integrated CMS for a financial services company',
    'portfolio.projects.p5.title': 'Brand Identity',
    'portfolio.projects.p5.description': 'Complete brand identity package for a tech startup, including logo, typography, and brand guidelines',
    'portfolio.projects.p6.title': 'Mobile App',
    'portfolio.projects.p6.description': 'Feature-rich mobile application for a health and wellness platform with personalized user experiences',
    'portfolio.testimonials.title': 'Client Testimonials',
    'portfolio.testimonials.subtitle': 'What our clients say about us',
    'portfolio.testimonials.t1.quote': 'The team exceeded our expectations. They not only delivered a beautiful website but improved our entire digital marketing game.',
    'portfolio.testimonials.t2.quote': 'The AI solution they developed for us has drastically improved our user engagement and conversion rates. Highly recommended!',
    'portfolio.testimonials.t3.quote': 'Professional, timely, and incredibly talented. They understood our vision and brought it to life with precision.',
    'portfolio.cta.title': 'Ready to Work on Your Project?',
    'portfolio.cta.description': 'Let\'s discuss how we can bring your ideas to life',
    'portfolio.cta.contact': 'Get in Touch',
    'portfolio.cta.schedule': 'Schedule a Call',
    
    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with us',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.success': 'Your message has been successfully sent!',
    'contact.error': 'An error occurred. Please try again later.',
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': 'We\'d love to hear from you',
    'contact.email.title': 'Email',
    'contact.email.description': 'Send us a message, we\'ll respond within 24 hours',
    'contact.phone.title': 'Phone',
    'contact.phone.description': 'Call us for immediate assistance with urgent inquiries',
    'contact.office.title': 'Office',
    'contact.office.description': 'Visit us at our main office for an in-person conversation',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Your Name',
    'contact.form.namePlaceholder': 'Enter your name',
    'contact.form.email': 'Your Email',
    'contact.form.emailPlaceholder': 'Enter your email',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'Enter subject',
    'contact.form.message': 'Your Message',
    'contact.form.messagePlaceholder': 'How can we help you?',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.success.title': 'Message Sent!',
    'contact.success.description': 'Thank you for your message. We\'ll get back to you as soon as possible.',
    'contact.error.title': 'Error',
    'contact.error.description': 'There was an error sending your message. Please try again later.',
    'contact.office.hoursTitle': 'Office Hours & Location',
    'contact.office.schedule': 'Schedule Appointment',
    'contact.office.monday': 'Monday - Friday',
    'contact.office.saturday': 'Saturday',
    'contact.office.sunday': 'Sunday',
    'contact.office.closed': 'Closed',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.subtitle': 'Answers to the most commonly asked questions',
    'contact.faq.q1': 'How do I start a project with you?',
    'contact.faq.a1': 'The first step is to contact us and tell us a bit about your project. We\'ll then arrange a call to discuss your requirements in detail and create a proposal.',
    'contact.faq.q2': 'How long does it take to complete a project?',
    'contact.faq.a2': 'Project duration heavily depends on scope and complexity. A simple website redesign might take 2-4 weeks, while more complex digital transformation projects can take 3-6 months or longer.',
    'contact.faq.q3': 'What payment terms do you offer?',
    'contact.faq.a3': 'We offer flexible payment terms, including flat rates for projects, hourly rates for ongoing work, and retainer models for continuous services. For larger projects, we typically work with a deposit and then milestone-based payments.',
    'contact.faq.q4': 'Do you work with clients outside of Germany?',
    'contact.faq.a4': 'Yes, we work with clients worldwide. Our team is accustomed to remote work and we use various tools to ensure effective communication and collaboration across different time zones.',
    
    // Footer
    'footer.rights': 'All Rights Reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.imprint': 'Imprint',
    'footer.cookies': 'Cookies',
    
    // Cookies
    'cookies.title': 'Cookie Policy',
    'cookies.subtitle': 'How we use cookies to enhance your browsing experience',
    'cookies.lastUpdated': 'Last updated',
    'cookies.whatAre.title': 'What are Cookies?',
    'cookies.whatAre.p1': 'Cookies are small text files that are stored on your computer or mobile device when you visit a website. They are widely used to make websites work more efficiently and provide information to the site owners.',
    'cookies.howWeUse.title': 'How We Use Cookies',
    'cookies.howWeUse.p1': 'We use cookies to enhance your browsing experience, analyze website performance, provide personalized content, and support our marketing efforts.',
    'cookies.types.title': 'Types of Cookies We Use',
    'cookies.types.account.title': 'Account-related Cookies',
    'cookies.types.account.p1': 'These cookies help us recognize you when you log in and remember your preferences for future visits.',
    'cookies.types.login.title': 'Login-related Cookies',
    'cookies.types.login.p1': 'These cookies are used to enable your login and maintain your session as you navigate our website.',
    'cookies.types.forms.title': 'Form-related Cookies',
    'cookies.types.forms.p1': 'These cookies store information you enter into forms on our website, such as contact forms or comments.',
    'cookies.types.site.title': 'Site Preferences',
    'cookies.types.site.p1': 'These cookies store your preferences like language settings so we can provide a personalized experience for future visits.',
    'cookies.thirdParty.title': 'Third-Party Cookies',
    'cookies.thirdParty.p1': 'We may also allow third-party cookies that help us analyze how visitors use our website and measure the effectiveness of our marketing efforts.',
    'cookies.thirdParty.analytics': 'Analytics cookies to understand how visitors interact with our website',
    'cookies.thirdParty.social': 'Social media cookies to enable content sharing',
    'cookies.disabling.title': 'Disabling Cookies',
    'cookies.disabling.p1': 'You can control and manage cookies in your browser settings. However, please note that disabling cookies may affect the functionality of our website.',
    'cookies.more.title': 'More Information',
    'cookies.more.p1': 'If you have any questions about our cookie policy or would like to learn more about how we process your personal data, please read our Privacy Policy.',
    'cookies.more.p2': 'For any inquiries or concerns, please contact us at:',
    'cookies.more.email': 'Email',
    'cookies.more.phone': 'Phone',
    'cookies.backButton': 'Back to Previous Page',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get language from local storage or use browser language
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'de' || savedLanguage === 'en')) {
      return savedLanguage;
    }
    return navigator.language.startsWith('de') ? 'de' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
