// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijxgpatgsturjetmlzkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqeGdwYXRnc3R1cmpldG1semt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDkyODQsImV4cCI6MjA1ODA4NTI4NH0.eptPzl3GT9YMObDKG-2bmpvLqezjtQY7yRaePA8hOJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);